export enum ConfigKey {
  NODE_ENV = 'NODE_ENV',

  HOST = 'HOST',
  PORT = 'PORT',

  CLIENT_URL = 'CLIENT_URL',

  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_DB = 'POSTGRES_DB',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_SYNCHRONIZE = 'POSTGRES_SYNCHRONIZE',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  STEAM_API_KEY = 'STEAM_API_KEY',

  AUTH_TOKEN_SECRET = 'AUTH_TOKEN_SECRET',
  AUTH_TOKEN_EXPIRATION = 'AUTH_TOKEN_EXPIRATION',
}
