export enum ItemRarity {
  CONSUMER_GRADE = 'CONSUMER_GRADE',
  INDUSTRIAL_GRADE = 'INDUSTRIAL_GRADE',
  MIL_SPEC = 'MIL_SPEC',
  RESTRICTED = 'RESTRICTED',
  CLASSIFIED = 'CLASSIFIED',
  COVERT = 'COVERT',
  CONTRABAND = 'CONTRABAND',
}
