export enum ConfigKey {
  NODE_ENV = 'NODE_ENV',

  HOST = 'HOST',
  PORT = 'PORT',

  CLIENT_URL = 'CLIENT_URL',
  COOKIE_DOMAIN = 'COOKIE_DOMAIN',

  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_DB = 'POSTGRES_DB',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_SYNCHRONIZE = 'POSTGRES_SYNCHRONIZE',

  AUTH_ACCESS_TOKEN_SECRET = 'AUTH_ACCESS_TOKEN_SECRET',
  AUTH_ACCESS_TOKEN_EXPIRATION = 'AUTH_ACCESS_TOKEN_EXPIRATION',
  AUTH_REFRESH_TOKEN_SECRET = 'AUTH_REFRESH_TOKEN_SECRET',
  AUTH_REFRESH_TOKEN_EXPIRATION = 'AUTH_REFRESH_TOKEN_EXPIRATION',
}
